### ISSUE TITLE
ERROR:root:Plex Authorization error

### ISSUE THREAD

**Issue by sidoverflow** [rnagabhyrava/plex-playlist-sync#62]
**Describe the bug**
`ERROR:root:Plex Authorization error` on spinning up the docker container. 

**To Reproduce**
1. Configuration: 
```
version: "2.1"
services:
  playlistSync:
    image: rnagabhyrava/plexplaylistsync:latest
    container_name: playlistSync
    volumes:
      - /home/user/music:/data
    environment:
      - PLEX_URL=http://IP:32400
      - PLEX_TOKEN=<X-Plex-Token>
      - WRITE_MISSING_AS_CSV=1 # Default 0, 1 = writes missing tracks from each playlist to a csv
      - APPEND_SERVICE_SUFFIX=1 # Default 1, 1 = appends the service name to the playlist name
      - ADD_PLAYLIST_POSTER=1 # Default 1, 1 = add poster for each playlist
      - ADD_PLAYLIST_DESCRIPTION=1 # Default 1, 1 = add description for each playlist
      - APPEND_INSTEAD_OF_SYNC=1 # Default 0, 1 = Sync tracks, 0 = Append only
      - SECONDS_TO_WAIT=84000
      - SPOTIFY_CLIENT_ID=<client_id>
      - SPOTIFY_CLIENT_SECRET=<client_secret>
      - DEEZER_USER_ID=<spotify user id>
      - DEEZER_PLAYLIST_ID= #<deezer playlist ids space seperated>
    restart: unless-stopped
```
2. Playlist(s) causing the issue:
All

**Expected behavior**
Playlists from spotify are synced on plex

**Screenshots**
![Screen Shot 2023-08-29 at 9 55 50 PM](https://github.com/rnagabhyrava/plex-playlist-sync/assets/59708815/8e2f30ee-fff8-4623-beef-22bf233eb67a)
